
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Month;
import java.time.Year;
import java.time.format.TextStyle;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Jose Eliud Bernal
 */
public class MainReportApart extends javax.swing.JPanel {

    /**
     * Creates new form Control
     */
    public MainReportApart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(406, 405));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(119, 171, 183));
        jPanel1.setMinimumSize(new java.awt.Dimension(530, 300));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(406, 405));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel1.setText("reporte de apartados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jPanel2.setBackground(new java.awt.Color(119, 171, 183));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("generar reporte ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 260, 30));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jPanel2.setBackground(new Color(29,62,83));
        jLabel2.setForeground(Color.white);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jPanel2.setBackground(new Color(119,171,183));
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            pdfAct();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(ReportSell.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked
    public void pdfAct() throws SQLException, IOException{
        try {
            Cone con = new Cone();
            Connection cn = (Connection) con.conexion();
            Document repVen = new Document(PageSize.LETTER);
            repVen.setMargins(72, 72, 72, 72);
            PdfWriter pdfNom = PdfWriter.getInstance(repVen, new FileOutputStream("C:/Users/Jose Eliud Bernal/Desktop/"
                    + "Ventas/Mensuales/Reporte de Apartados.pdf"));
            repVen.open();
            Font priFue = new Font(Font.FontFamily.TIMES_ROMAN, 14, Font.BOLD);
            Font segFue = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);
            Font terFue = new Font(Font.FontFamily.TIMES_ROMAN, 12);
            Paragraph titulo = new Paragraph("Reporte de Apartados - " , priFue);
            titulo.setAlignment(Element.ALIGN_CENTER);
            repVen.add(titulo);
            Paragraph periodo = new Paragraph("Periodo: Activo", segFue);
            periodo.setAlignment(Element.ALIGN_CENTER);
            repVen.add(new Paragraph("\n"));
            repVen.add(periodo);
            repVen.add(new Paragraph("\n"));
            Paragraph resGen = new Paragraph("Resumen General ", segFue);   
            resGen.setAlignment(Element.ALIGN_LEFT);
            repVen.add(resGen);
            //Valor de todas las ventas mensuales
            PreparedStatement conTot = cn.prepareStatement("SELECT SUM(Abono) AS TotalAbonos "
                    + "FROM apartado");
            ResultSet rs = conTot.executeQuery();
            String venTot = rs.next() ? rs.getString("TotalAbonos") : null;
            Paragraph totVen = new Paragraph("Abonos totales: $" + venTot, terFue);
            repVen.add(totVen);
            //Cantidad de ventas mensuales
            PreparedStatement canVen = cn.prepareStatement("SELECT COUNT(*) AS CantidadDeApartados FROM apartado");
            ResultSet rs1 = canVen.executeQuery();
            String canTot = rs1.next() ? rs1.getString("CantidadDeApartados") : null;
            Paragraph totCan = new Paragraph("Cantidad de apartados: " + canTot, terFue);
            repVen.add(totCan);
            //Consultar todas las ventas
            PreparedStatement totVenMes = cn.prepareStatement("SELECT cod_a, Abono, Saldo, Total, Fecha, Cliente_id "
                    + "FROM apartado GROUP BY cod_a, Abono, Saldo, Total, Fecha, Cliente_id");
            ResultSet rs5 = totVenMes.executeQuery();
            PdfPTable tabTotVen = new PdfPTable(5);
            tabTotVen.addCell(new Phrase ("Apartado", segFue));
            tabTotVen.addCell(new Phrase ("Abono", segFue));
            tabTotVen.addCell(new Phrase ("Saldo", segFue));
            tabTotVen.addCell(new Phrase ("Total", segFue));
            tabTotVen.addCell(new Phrase ("Cliente", segFue));
            while (rs5.next()) {
                tabTotVen.addCell(new Phrase(rs5.getString("cod_a"), terFue));
                tabTotVen.addCell(new Phrase(rs5.getString("Abono"), terFue));
                tabTotVen.addCell(new Phrase(rs5.getString("Saldo"), terFue));
                tabTotVen.addCell(new Phrase(rs5.getString("Total"), terFue));
                tabTotVen.addCell(new Phrase(rs5.getString("Cliente_id"), terFue));
            }
            repVen.add(new Paragraph("Total de apartados ", terFue));
            repVen.add(new Paragraph("\n"));
            repVen.add(tabTotVen);
            repVen.close();
            String rutaPDF = "C:/Users/Jose Eliud Bernal/Desktop/"
                    + "Ventas/Mensuales/Reporte de Apartados.pdf";
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                File archivoPDF = new File(rutaPDF);
                if (archivoPDF.exists()) {      
                    desktop.open(archivoPDF);
                } else {
                    System.err.println("El archivo no existe: " + rutaPDF);
                }
            }
        } catch (DocumentException | FileNotFoundException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    Object getContentPane() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
